In [24]:
#Data Clean-up
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress

df = pd.read_csv('Resources/all.csv')
df = pd.DataFrame(df)
df.columns

Index(['Unnamed: 0', 'State', 'District', 'Persons', 'Males', 'Females',
       'Growth..1991...2001.', 'Rural', 'Urban', 'Scheduled.Caste.population',
       'Percentage...SC.to.total', 'Number.of.households',
       'Household.size..per.household.', 'Sex.ratio..females.per.1000.males.',
       'Sex.ratio..0.6.years.', 'Scheduled.Tribe.population',
       'Percentage.to.total.population..ST.', 'Persons..literate',
       'Males..Literate', 'Females..Literate', 'Persons..literacy.rate',
       'Males..Literatacy.Rate', 'Females..Literacy.Rate', 'Total.Educated',
       'Data.without.level', 'Below.Primary', 'Primary', 'Middle',
       'Matric.Higher.Secondary.Diploma', 'Graduate.and.Above', 'X0...4.years',
       'X5...14.years', 'X15...59.years', 'X60.years.and.above..Incl..A.N.S..',
       'Total.workers', 'Main.workers', 'Marginal.workers', 'Non.workers',
       'SC.1.Name', 'SC.1.Population', 'SC.2.Name', 'SC.2.Population',
       'SC.3.Name', 'SC.3.Population', 'Religeon.1.Name',
       'Religeon.1.Population', 'Religeon.2.Name', 'Religeon.2.Population',
       'Religeon.3.Name', 'Religeon.3.Population', 'ST.1.Name',
       'ST.1.Population', 'ST.2.Name', 'ST.2.Population', 'ST.3.Name',
       'ST.3.Population', 'Imp.Town.1.Name', 'Imp.Town.1.Population',
       'Imp.Town.2.Name', 'Imp.Town.2.Population', 'Imp.Town.3.Name',
       'Imp.Town.3.Population', 'Total.Inhabited.Villages',
       'Drinking.water.facilities', 'Safe.Drinking.water',
       'Electricity..Power.Supply.', 'Electricity..domestic.',
       'Electricity..Agriculture.', 'Primary.school', 'Middle.schools',
       'Secondary.Sr.Secondary.schools', 'College', 'Medical.facility',
       'Primary.Health.Centre', 'Primary.Health.Sub.Centre',
       'Post..telegraph.and.telephone.facility', 'Bus.services',
       'Paved.approach.road', 'Mud.approach.road', 'Permanent.House',
       'Semi.permanent.House', 'Temporary.House'],
      dtype='object')

In [25]:
#Drop the columns filled with a ton of NAs
df = df.drop(['Urban','Scheduled.Caste.population','Percentage...SC.to.total','Scheduled.Tribe.population',
              'Percentage.to.total.population..ST.','Males..Literate','Females..Literate','Males..Literatacy.Rate','Household.size..per.household.',
              'Females..Literacy.Rate','X0...4.years','X5...14.years','X15...59.years','X60.years.and.above..Incl..A.N.S..',
              'Total.workers','Main.workers','Marginal.workers','Non.workers','SC.1.Name','SC.1.Population','SC.2.Name',
              'SC.2.Population','SC.3.Name','SC.3.Population','ST.1.Name','ST.1.Population','ST.2.Name','ST.2.Population',
              'ST.3.Name','ST.3.Population','Imp.Town.1.Name','Imp.Town.1.Population','Imp.Town.2.Name','Imp.Town.2.Population',
              'Imp.Town.3.Name','Imp.Town.3.Population','Total.Inhabited.Villages','Primary.Health.Sub.Centre',
              'College','Electricity..domestic.','Electricity..Agriculture.'],axis=1)
df.head()

,Unnamed: 0,State,District,Persons,Males,Females,Growth..1991...2001.,Rural,Number.of.households,Sex.ratio..females.per.1000.males.,Sex.ratio..0.6.years.,Persons..literate,Persons..literacy.rate,Total.Educated,Data.without.level,Below.Primary,Primary,Middle,Matric.Higher.Secondary.Diploma,Graduate.and.Above,Religeon.1.Name,Religeon.1.Population,Religeon.2.Name,Religeon.2.Population,Religeon.3.Name,Religeon.3.Population,Drinking.water.facilities,Safe.Drinking.water,Electricity..Power.Supply.,Primary.school,Middle.schools,Secondary.Sr.Secondary.schools,Medical.facility,Primary.Health.Centre,Post..telegraph.and.telephone.facility,Bus.services,Paved.approach.road,Mud.approach.road,Permanent.House,Semi.permanent.House,Temporary.House
0,1,AN,"District Andamans (01), Andaman & Nicobar Islands (35)",314084,170319,143765,30.14,197886,70167.0,844.0,959.0,226600,82.49,226600.0,1623.0,48339.0,62233.0,49731.0,50748.0,13909.0,1.Hindus,235862,2.Christians,49033,3.Muslims,27134,331.0,293.0,233.0,185.0,83,71,102,16,161.0,187,201,243,28.7,39.1,32.0
1,2,AN,"District Nicobars (02), Andaman & Nicobar Islands (35)",42068,22653,19415,7.19,42068,8075.0,857.0,936.0,26535,72.35,26535.0,346.0,5062.0,8544.0,6439.0,5150.0,994.0,1.Christians,28145,2.Hindus,10727,3.Muslims,2131,169.0,163.0,96.0,53.0,25,22,38,4,36.0,49,51,111,28.0,33.3,38.7
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986,524649.0,989.0,962.0,1112189,52.68,1112189.0,46680.0,347433.0,305503.0,114789.0,254169.0,43564.0,NaN,2207843,NaN,236844,NaN,24392,1585.0,1580.0,1585.0,1521.0,429,196,976,61,558.0,814,979,544,53.0,39.9,7.0
3,4,Andhra,"District Nizamabad (02), Andhra Pradesh (28)",2345685,1162905,1182780,14.98,1920947,484588.0,1017.0,958.0,1044788,52.02,1044788.0,43604.0,288554.0,304556.0,106517.0,249549.0,51926.0,1.Hindus,1983275,2.Muslims,338824,3.Christians,16204,854.0,854.0,854.0,839.0,417,256,614,50,602.0,746,760,82,52.8,37.6,9.6
4,5,Andhra,"District Karimnagar (03), Andhra Pradesh (28)",3491822,1747968,1743854,14.47,2813010,813797.0,998.0,961.0,1661089,54.90,1661089.0,57595.0,445208.0,478883.0,189226.0,409110.0,81001.0,1.Hindus,3251834,2.Muslims,213811,3.Christians,20576,1047.0,1046.0,1047.0,1039.0,668,391,863,70,795.0,912,823,218,55.8,36.4,7.8

In [26]:
#Change '-' to NaN so that we can drop those 
df = df.replace('-',np.nan)
df.head()

,Unnamed: 0,State,District,Persons,Males,Females,Growth..1991...2001.,Rural,Number.of.households,Sex.ratio..females.per.1000.males.,Sex.ratio..0.6.years.,Persons..literate,Persons..literacy.rate,Total.Educated,Data.without.level,Below.Primary,Primary,Middle,Matric.Higher.Secondary.Diploma,Graduate.and.Above,Religeon.1.Name,Religeon.1.Population,Religeon.2.Name,Religeon.2.Population,Religeon.3.Name,Religeon.3.Population,Drinking.water.facilities,Safe.Drinking.water,Electricity..Power.Supply.,Primary.school,Middle.schools,Secondary.Sr.Secondary.schools,Medical.facility,Primary.Health.Centre,Post..telegraph.and.telephone.facility,Bus.services,Paved.approach.road,Mud.approach.road,Permanent.House,Semi.permanent.House,Temporary.House
0,1,AN,"District Andamans (01), Andaman & Nicobar Islands (35)",314084,170319,143765,30.14,197886,70167.0,844.0,959.0,226600,82.49,226600.0,1623.0,48339.0,62233.0,49731.0,50748.0,13909.0,1.Hindus,235862,2.Christians,49033,3.Muslims,27134,331.0,293.0,233.0,185.0,83,71,102,16,161.0,187,201,243,28.7,39.1,32.0
1,2,AN,"District Nicobars (02), Andaman & Nicobar Islands (35)",42068,22653,19415,7.19,42068,8075.0,857.0,936.0,26535,72.35,26535.0,346.0,5062.0,8544.0,6439.0,5150.0,994.0,1.Christians,28145,2.Hindus,10727,3.Muslims,2131,169.0,163.0,96.0,53.0,25,22,38,4,36.0,49,51,111,28.0,33.3,38.7
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986,524649.0,989.0,962.0,1112189,52.68,1112189.0,46680.0,347433.0,305503.0,114789.0,254169.0,43564.0,NaN,2207843,NaN,236844,NaN,24392,1585.0,1580.0,1585.0,1521.0,429,196,976,61,558.0,814,979,544,53.0,39.9,7.0
3,4,Andhra,"District Nizamabad (02), Andhra Pradesh (28)",2345685,1162905,1182780,14.98,1920947,484588.0,1017.0,958.0,1044788,52.02,1044788.0,43604.0,288554.0,304556.0,106517.0,249549.0,51926.0,1.Hindus,1983275,2.Muslims,338824,3.Christians,16204,854.0,854.0,854.0,839.0,417,256,614,50,602.0,746,760,82,52.8,37.6,9.6
4,5,Andhra,"District Karimnagar (03), Andhra Pradesh (28)",3491822,1747968,1743854,14.47,2813010,813797.0,998.0,961.0,1661089,54.90,1661089.0,57595.0,445208.0,478883.0,189226.0,409110.0,81001.0,1.Hindus,3251834,2.Muslims,213811,3.Christians,20576,1047.0,1046.0,1047.0,1039.0,668,391,863,70,795.0,912,823,218,55.8,36.4,7.8

In [27]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)
df.dtypes

Unnamed: 0                                int64
State                                     object
District                                  object
Persons                                   int64
Males                                     int64
Females                                   int64
Growth..1991...2001.                      object
Rural                                     object
Number.of.households                      float64
Sex.ratio..females.per.1000.males.        float64
Sex.ratio..0.6.years.                     float64
Persons..literate                         int64
Persons..literacy.rate                    float64
Total.Educated                            float64
Data.without.level                        float64
Below.Primary                             float64
Primary                                   float64
Middle                                    float64
Matric.Higher.Secondary.Diploma           float64
Graduate.and.Above                        float64
Religeon.1.Name                           object
Religeon.1.Population                     int64
Religeon.2.Name                           object
Religeon.2.Population                     int64
Religeon.3.Name                           object
Religeon.3.Population                     int64
Drinking.water.facilities                 float64
Safe.Drinking.water                       float64
Electricity..Power.Supply.                float64
Primary.school                            float64
Middle.schools                            object
Secondary.Sr.Secondary.schools            object
Medical.facility                          object
Primary.Health.Centre                     object
Post..telegraph.and.telephone.facility    float64
Bus.services                              object
Paved.approach.road                       object
Mud.approach.road                         object
Permanent.House                           float64
Semi.permanent.House                      float64
Temporary.House                           float64
dtype: object

In [28]:
#Rename Columns
df = df.rename(columns={'Growth..1991...2001.':'Growth Rate',
                        'Number.of.households':'Number of Households',                       'Sex.ratio..females.per.1000.males.':'Females per 1000 Males',
                        'Sex.ratio..0.6.years.':'Sex Ratio,0-6 Year Olds',
                        'Persons..literate':'Literate Persons',
                        'Persons..literacy.rate':'Literacy Rate',
                        'Total.Educated': 'Total Educated',
                        'Data.without.level':'Total Uneducated',
                        'Below.Primary':'Below Primary',
                        'Graduate.and.Above':'Graduate Degree or Above',
                        'Religeon.1.Name':'1st Religion Name',
                        'Religeon.1.Population':'1st Religion Population',
                        'Religeon.2.Name':'2nd Religion Name',
                        'Religeon.2.Population':'2nd Religion Population',
                        'Religeon.3.Name':'3rd Religion Name',
                        'Religeon.3.Population':'3rd Religion Population',
                        'Drinking.water.facilities':'Drinking Water Facilities',
                        'Safe.Drinking.water':'Safe Drinking Water Facilities',
                        'Electricity..Power.Supply.':'Electric Supply',
                        'Primary.school':'Primary School',
                        'Middle.schools':'Middle Schools',
                        'Secondary.Sr.Secondary.schools':'Secondary Schools',
                        'Medical.facility':'Medical Facilities',
                        'Primary.Health.Centre':'Primary Health Centers',
                        'Post..telegraph.and.telephone.facility':'Communication Facilities',
                        'Bus.services':'Bus Services',
                        'Paved.approach.road':'Paved Approach Road',
                        'Mud.approach.road':'Mud Approach Road',
                        'Permanent.House':'Permanent Housing Rate',
                        'Semi.permanent.House':'Semi-Permanent Housing Rate',
                        'Temporary.House':'Temporary Housing Rate'})
df.head()

,Unnamed: 0,State,District,Persons,Males,Females,Growth Rate,Rural,Number of Households,Females per 1000 Males,"Sex Ratio,0-6 Year Olds",Literate Persons,Literacy Rate,Total Educated,Total Uneducated,Below Primary,Primary,Middle,Matric.Higher.Secondary.Diploma,Graduate Degree or Above,1st Religion Name,1st Religion Population,2nd Religion Name,2nd Religion Population,3rd Religion Name,3rd Religion Population,Drinking Water Facilities,Safe Drinking Water Facilities,Electric Supply,Primary School,Middle Schools,Secondary Schools,Medical Facilities,Primary Health Centers,Communication Facilities,Bus Services,Paved Approach Road,Mud Approach Road,Permanent Housing Rate,Semi-Permanent Housing Rate,Temporary Housing Rate
0,1,AN,"District Andamans (01), Andaman & Nicobar Islands (35)",314084,170319,143765,30.14,197886,70167.0,844.0,959.0,226600,82.49,226600.0,1623.0,48339.0,62233.0,49731.0,50748.0,13909.0,1.Hindus,235862,2.Christians,49033,3.Muslims,27134,331.0,293.0,233.0,185.0,83,71,102,16,161.0,187,201,243,28.7,39.1,32.0
1,2,AN,"District Nicobars (02), Andaman & Nicobar Islands (35)",42068,22653,19415,7.19,42068,8075.0,857.0,936.0,26535,72.35,26535.0,346.0,5062.0,8544.0,6439.0,5150.0,994.0,1.Christians,28145,2.Hindus,10727,3.Muslims,2131,169.0,163.0,96.0,53.0,25,22,38,4,36.0,49,51,111,28.0,33.3,38.7
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986,524649.0,989.0,962.0,1112189,52.68,1112189.0,46680.0,347433.0,305503.0,114789.0,254169.0,43564.0,NaN,2207843,NaN,236844,NaN,24392,1585.0,1580.0,1585.0,1521.0,429,196,976,61,558.0,814,979,544,53.0,39.9,7.0
3,4,Andhra,"District Nizamabad (02), Andhra Pradesh (28)",2345685,1162905,1182780,14.98,1920947,484588.0,1017.0,958.0,1044788,52.02,1044788.0,43604.0,288554.0,304556.0,106517.0,249549.0,51926.0,1.Hindus,1983275,2.Muslims,338824,3.Christians,16204,854.0,854.0,854.0,839.0,417,256,614,50,602.0,746,760,82,52.8,37.6,9.6
4,5,Andhra,"District Karimnagar (03), Andhra Pradesh (28)",3491822,1747968,1743854,14.47,2813010,813797.0,998.0,961.0,1661089,54.90,1661089.0,57595.0,445208.0,478883.0,189226.0,409110.0,81001.0,1.Hindus,3251834,2.Muslims,213811,3.Christians,20576,1047.0,1046.0,1047.0,1039.0,668,391,863,70,795.0,912,823,218,55.8,36.4,7.8

In [29]:
#Remove the leading numbers from religion names
df['1st Religion Name'] = df['1st Religion Name'].str.replace('1.','')
df['2nd Religion Name'] = df['2nd Religion Name'].str.replace('2.','')
df['3rd Religion Name'] = df['3rd Religion Name'].str.replace('3.','')
df.head()

,Unnamed: 0,State,District,Persons,Males,Females,Growth Rate,Rural,Number of Households,Females per 1000 Males,"Sex Ratio,0-6 Year Olds",Literate Persons,Literacy Rate,Total Educated,Total Uneducated,Below Primary,Primary,Middle,Matric.Higher.Secondary.Diploma,Graduate Degree or Above,1st Religion Name,1st Religion Population,2nd Religion Name,2nd Religion Population,3rd Religion Name,3rd Religion Population,Drinking Water Facilities,Safe Drinking Water Facilities,Electric Supply,Primary School,Middle Schools,Secondary Schools,Medical Facilities,Primary Health Centers,Communication Facilities,Bus Services,Paved Approach Road,Mud Approach Road,Permanent Housing Rate,Semi-Permanent Housing Rate,Temporary Housing Rate
0,1,AN,"District Andamans (01), Andaman & Nicobar Islands (35)",314084,170319,143765,30.14,197886,70167.0,844.0,959.0,226600,82.49,226600.0,1623.0,48339.0,62233.0,49731.0,50748.0,13909.0,Hindus,235862,Christians,49033,Muslims,27134,331.0,293.0,233.0,185.0,83,71,102,16,161.0,187,201,243,28.7,39.1,32.0
1,2,AN,"District Nicobars (02), Andaman & Nicobar Islands (35)",42068,22653,19415,7.19,42068,8075.0,857.0,936.0,26535,72.35,26535.0,346.0,5062.0,8544.0,6439.0,5150.0,994.0,Christians,28145,Hindus,10727,Muslims,2131,169.0,163.0,96.0,53.0,25,22,38,4,36.0,49,51,111,28.0,33.3,38.7
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986,524649.0,989.0,962.0,1112189,52.68,1112189.0,46680.0,347433.0,305503.0,114789.0,254169.0,43564.0,NaN,2207843,NaN,236844,NaN,24392,1585.0,1580.0,1585.0,1521.0,429,196,976,61,558.0,814,979,544,53.0,39.9,7.0
3,4,Andhra,"District Nizamabad (02), Andhra Pradesh (28)",2345685,1162905,1182780,14.98,1920947,484588.0,1017.0,958.0,1044788,52.02,1044788.0,43604.0,288554.0,304556.0,106517.0,249549.0,51926.0,Hindus,1983275,Muslims,338824,Christians,16204,854.0,854.0,854.0,839.0,417,256,614,50,602.0,746,760,82,52.8,37.6,9.6
4,5,Andhra,"District Karimnagar (03), Andhra Pradesh (28)",3491822,1747968,1743854,14.47,2813010,813797.0,998.0,961.0,1661089,54.90,1661089.0,57595.0,445208.0,478883.0,189226.0,409110.0,81001.0,Hindus,3251834,Muslims,213811,Christians,20576,1047.0,1046.0,1047.0,1039.0,668,391,863,70,795.0,912,823,218,55.8,36.4,7.8

In [30]:
df.dtypes

Unnamed: 0                         int64
State                              object
District                           object
Persons                            int64
Males                              int64
Females                            int64
Growth Rate                        object
Rural                              object
Number of Households               float64
Females per 1000 Males             float64
Sex Ratio,0-6 Year Olds            float64
Literate Persons                   int64
Literacy Rate                      float64
Total Educated                     float64
Total Uneducated                   float64
Below Primary                      float64
Primary                            float64
Middle                             float64
Matric.Higher.Secondary.Diploma    float64
Graduate Degree or Above           float64
1st Religion Name                  object
1st Religion Population            int64
2nd Religion Name                  object
2nd Religion Population            int64
3rd Religion Name                  object
3rd Religion Population            int64
Drinking Water Facilities          float64
Safe Drinking Water Facilities     float64
Electric Supply                    float64
Primary School                     float64
Middle Schools                     object
Secondary Schools                  object
Medical Facilities                 object
Primary Health Centers             object
Communication Facilities           float64
Bus Services                       object
Paved Approach Road                object
Mud Approach Road                  object
Permanent Housing Rate             float64
Semi-Permanent Housing Rate        float64
Temporary Housing Rate             float64
dtype: object

In [31]:
#Create some new columns for the future analysis
df['Rate of Clean Water Facilities'] = df.loc[:,'Safe Drinking Water Facilities']/df.loc[:,'Drinking Water Facilities']
df['Communication Facilities per 1000 People'] = (df.loc[:,'Communication Facilities']/df.loc[:,'Persons'])*1000
df['Drinking Facilities per 1000 People'] = (df.loc[:,'Drinking Water Facilities']/df.loc[:,'Persons'])*1000
df['Medical Facilities'] = pd.to_numeric(df['Medical Facilities'])
df['Medical Facilities per 1000 People'] = (df.loc[:,'Medical Facilities']/df.loc[:,'Persons'])*1000
df['Permanent Housing Rate'] = df.loc[:,'Permanent Housing Rate']/100
df['Semi-Permanent Housing Rate'] = df.loc[:,'Semi-Permanent Housing Rate']/100
df['Temporary Housing Rate'] = df.loc[:,'Temporary Housing Rate']/100
df['Permanent Housing'] = round(df.loc[:,'Permanent Housing Rate']*df.loc[:,'Persons'],0)
df['Semi-Permanent Housing'] = round(df.loc[:,'Semi-Permanent Housing Rate']*df.loc[:,'Persons'],0)
df['Temporary Housing'] = round(df.loc[:,'Temporary Housing Rate']*df.loc[:,'Persons'],0)
df['Total Housing'] = df.loc[:,'Permanent Housing'] + df.loc[:,'Semi-Permanent Housing'] + df.loc[:,'Temporary Housing']
df['Religion 1 Percent Population'] = df.loc[:,'1st Religion Population']/df.loc[:,'Persons']
df['Religion 2 Percent Population'] = df.loc[:,'2nd Religion Population']/df.loc[:,'Persons']
df['Religion 3 Percent Population'] = df.loc[:,'3rd Religion Population']/df.loc[:,'Persons']
df['Rural'] = pd.to_numeric(df['Rural'])
df['Rural Percent Population'] = df.loc[:,'Rural']/df.loc[:,'Persons']
df['Female to Male Ratio'] = df.loc[:,'Females per 1000 Males']/1000
df['Persons per Household'] = round(df.loc[:,'Persons']/df.loc[:,'Number of Households'],2)
df.head()

,Unnamed: 0,State,District,Persons,Males,Females,Growth Rate,Rural,Number of Households,Females per 1000 Males,"Sex Ratio,0-6 Year Olds",Literate Persons,Literacy Rate,Total Educated,Total Uneducated,Below Primary,Primary,Middle,Matric.Higher.Secondary.Diploma,Graduate Degree or Above,1st Religion Name,1st Religion Population,2nd Religion Name,2nd Religion Population,3rd Religion Name,3rd Religion Population,Drinking Water Facilities,Safe Drinking Water Facilities,Electric Supply,Primary School,Middle Schools,Secondary Schools,Medical Facilities,Primary Health Centers,Communication Facilities,Bus Services,Paved Approach Road,Mud Approach Road,Permanent Housing Rate,Semi-Permanent Housing Rate,Temporary Housing Rate,Rate of Clean Water Facilities,Communication Facilities per 1000 People,Drinking Facilities per 1000 People,Medical Facilities per 1000 People,Permanent Housing,Semi-Permanent Housing,Temporary Housing,Total Housing,Religion 1 Percent Population,Religion 2 Percent Population,Religion 3 Percent Population,Rural Percent Population,Female to Male Ratio,Persons per Household
0,1,AN,"District Andamans (01), Andaman & Nicobar Islands (35)",314084,170319,143765,30.14,197886.0,70167.0,844.0,959.0,226600,82.49,226600.0,1623.0,48339.0,62233.0,49731.0,50748.0,13909.0,Hindus,235862,Christians,49033,Muslims,27134,331.0,293.0,233.0,185.0,83,71,102.0,16,161.0,187,201,243,0.287,0.391,0.320,0.885196,0.512602,1.053858,0.324754,90142.0,122807.0,100507.0,313456.0,0.750952,0.156114,0.086391,0.630042,0.844,4.48
1,2,AN,"District Nicobars (02), Andaman & Nicobar Islands (35)",42068,22653,19415,7.19,42068.0,8075.0,857.0,936.0,26535,72.35,26535.0,346.0,5062.0,8544.0,6439.0,5150.0,994.0,Christians,28145,Hindus,10727,Muslims,2131,169.0,163.0,96.0,53.0,25,22,38.0,4,36.0,49,51,111,0.280,0.333,0.387,0.964497,0.855757,4.017305,0.903299,11779.0,14009.0,16280.0,42068.0,0.669036,0.254992,0.050656,1.000000,0.857,5.21
2,3,Andhra,"District Adilabad (01), Andhra Pradesh (28)",2488003,1250958,1237045,19.06,1827986.0,524649.0,989.0,962.0,1112189,52.68,1112189.0,46680.0,347433.0,305503.0,114789.0,254169.0,43564.0,NaN,2207843,NaN,236844,NaN,24392,1585.0,1580.0,1585.0,1521.0,429,196,976.0,61,558.0,814,979,544,0.530,0.399,0.070,0.996845,0.224276,0.637057,0.392282,1318642.0,992713.0,174160.0,2485515.0,0.887396,0.095194,0.009804,0.734720,0.989,4.74
3,4,Andhra,"District Nizamabad (02), Andhra Pradesh (28)",2345685,1162905,1182780,14.98,1920947.0,484588.0,1017.0,958.0,1044788,52.02,1044788.0,43604.0,288554.0,304556.0,106517.0,249549.0,51926.0,Hindus,1983275,Muslims,338824,Christians,16204,854.0,854.0,854.0,839.0,417,256,614.0,50,602.0,746,760,82,0.528,0.376,0.096,1.000000,0.256641,0.364073,0.261757,1238522.0,881978.0,225186.0,2345686.0,0.845499,0.144446,0.006908,0.818928,1.017,4.84
4,5,Andhra,"District Karimnagar (03), Andhra Pradesh (28)",3491822,1747968,1743854,14.47,2813010.0,813797.0,998.0,961.0,1661089,54.90,1661089.0,57595.0,445208.0,478883.0,189226.0,409110.0,81001.0,Hindus,3251834,Muslims,213811,Christians,20576,1047.0,1046.0,1047.0,1039.0,668,391,863.0,70,795.0,912,823,218,0.558,0.364,0.078,0.999045,0.227675,0.299843,0.247149,1948437.0,1271023.0,272362.0,3491822.0,0.931271,0.061232,0.005893,0.805599,0.998,4.29

In [32]:
#Convert Growth Rate to decimal
df['Growth Rate'] = df['Growth Rate'].str.replace('(','-')
df['Growth Rate'] = df['Growth Rate'].str.replace(')','')
df['Growth Rate'] = pd.to_numeric(df['Growth Rate'])
df['Growth Rate'] = round(df.loc[:,'Growth Rate']/100,2)

In [35]:
#Drop the NAs
df = df.dropna()
df.head()
#df['District Name'] = df['District'].str.split('').str[1]
df['District Name'] = df.loc[:,'District'].str.split('(').str[0]
df.head()

,Unnamed: 0,State,District,Persons,Males,Females,Growth Rate,Rural,Number of Households,Females per 1000 Males,"Sex Ratio,0-6 Year Olds",Literate Persons,Literacy Rate,Total Educated,Total Uneducated,Below Primary,Primary,Middle,Matric.Higher.Secondary.Diploma,Graduate Degree or Above,1st Religion Name,1st Religion Population,2nd Religion Name,2nd Religion Population,3rd Religion Name,3rd Religion Population,Drinking Water Facilities,Safe Drinking Water Facilities,Electric Supply,Primary School,Middle Schools,Secondary Schools,Medical Facilities,Primary Health Centers,Communication Facilities,Bus Services,Paved Approach Road,Mud Approach Road,Permanent Housing Rate,Semi-Permanent Housing Rate,Temporary Housing Rate,Rate of Clean Water Facilities,Communication Facilities per 1000 People,Drinking Facilities per 1000 People,Medical Facilities per 1000 People,Permanent Housing,Semi-Permanent Housing,Temporary Housing,Total Housing,Religion 1 Percent Population,Religion 2 Percent Population,Religion 3 Percent Population,Rural Percent Population,Female to Male Ratio,Persons per Household,District Name
0,1,AN,"District Andamans (01), Andaman & Nicobar Islands (35)",314084,170319,143765,0.30,197886.0,70167.0,844.0,959.0,226600,82.49,226600.0,1623.0,48339.0,62233.0,49731.0,50748.0,13909.0,Hindus,235862,Christians,49033,Muslims,27134,331.0,293.0,233.0,185.0,83,71,102.0,16,161.0,187,201,243,0.287,0.391,0.320,0.885196,0.512602,1.053858,0.324754,90142.0,122807.0,100507.0,313456.0,0.750952,0.156114,0.086391,0.630042,0.844,4.48,District Andamans
1,2,AN,"District Nicobars (02), Andaman & Nicobar Islands (35)",42068,22653,19415,0.07,42068.0,8075.0,857.0,936.0,26535,72.35,26535.0,346.0,5062.0,8544.0,6439.0,5150.0,994.0,Christians,28145,Hindus,10727,Muslims,2131,169.0,163.0,96.0,53.0,25,22,38.0,4,36.0,49,51,111,0.280,0.333,0.387,0.964497,0.855757,4.017305,0.903299,11779.0,14009.0,16280.0,42068.0,0.669036,0.254992,0.050656,1.000000,0.857,5.21,District Nicobars
3,4,Andhra,"District Nizamabad (02), Andhra Pradesh (28)",2345685,1162905,1182780,0.15,1920947.0,484588.0,1017.0,958.0,1044788,52.02,1044788.0,43604.0,288554.0,304556.0,106517.0,249549.0,51926.0,Hindus,1983275,Muslims,338824,Christians,16204,854.0,854.0,854.0,839.0,417,256,614.0,50,602.0,746,760,82,0.528,0.376,0.096,1.000000,0.256641,0.364073,0.261757,1238522.0,881978.0,225186.0,2345686.0,0.845499,0.144446,0.006908,0.818928,1.017,4.84,District Nizamabad
4,5,Andhra,"District Karimnagar (03), Andhra Pradesh (28)",3491822,1747968,1743854,0.14,2813010.0,813797.0,998.0,961.0,1661089,54.90,1661089.0,57595.0,445208.0,478883.0,189226.0,409110.0,81001.0,Hindus,3251834,Muslims,213811,Christians,20576,1047.0,1046.0,1047.0,1039.0,668,391,863.0,70,795.0,912,823,218,0.558,0.364,0.078,0.999045,0.227675,0.299843,0.247149,1948437.0,1271023.0,272362.0,3491822.0,0.931271,0.061232,0.005893,0.805599,0.998,4.29,District Karimnagar
5,6,Andhra,"District Medak (04), Andhra Pradesh (28)",2670097,1352446,1317651,0.17,2286573.0,521018.0,974.0,964.0,1171134,51.65,1171134.0,56841.0,339163.0,322529.0,118592.0,282352.0,51608.0,Hindus,2334169,Muslims,296486,Christians,34651,1225.0,1225.0,1225.0,1215.0,555,274,659.0,58,803.0,1007,978,239,0.493,0.426,0.081,1.000000,0.300738,0.458785,0.246808,1316358.0,1137461.0,216278.0,2670097.0,0.874189,0.111039,0.012977,0.856363,0.974,5.12,District Medak

In [34]:
#Export as 'cleaned.csv'
df.to_csv("Resources/cleaned.csv", index=False, header=True)